<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sav_librarymvc_example0"
 *
 * Auto generated by SAV Library Kickstarter 11-02-23
 *
 ***************************************************************/
 
$EM_CONF[$_EXTKEY] = [
    'title' => 'SAV Library Mvc Example0 - Test',
    'description' => 'An extension to illustrate the SAV Library Mvc',
    'category' => 'plugin',
    'author' => 'Laurent Foulloy',
    'author_email' => 'yolf.typo3@orange.fr',
    'author_company' => '',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 1,
    'version' => '11.5.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.28-11.5.99',
            'sav_library_mvc' => '10.4.0-0.0.0'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
