routeEnhancers:
  SavLibrarymvcExample0:
    type: Extbase
    extension: SavLibrarymvcExample0
    plugin: Default
    routes:
      - routePath: '/savlibrarymvcexample0/test'
        _controller: 'Test::list'
      - routePath: '/savlibrarymvcexample0/test/{special}'
        _controller: 'Test::list'
      - routePath: '/savlibrarymvcexample0/test/single/{special}'
        _controller: 'Test::single'
      - routePath: '/savlibrarymvcexample0/test/edit/{special}'
        _controller: 'Test::edit'
      - routePath: '/savlibrarymvcexample0/test/delete/{special}'
        _controller: 'Test::delete'
      - routePath: '/savlibrarymvcexample0/test/subform/delete/{special}'
        _controller: 'Test::deleteInSubform'
      - routePath: '/savlibrarymvcexample0/test/subform/up/{special}'
        _controller: 'Test::upInSubform'
      - routePath: '/savlibrarymvcexample0/test/subform/down/{special}'
        _controller: 'Test::downInSubform'
      - routePath: '/savlibrarymvcexample0/test/file/delete/{special}'
        _controller: 'Test::deleteFile'
      - routePath: '/savlibrarymvcexample0/test/export/{special}'
        _controller: 'Test::export'
    requirements:
      special: '[a-z0-9\-]+'
     